### ISSUE TITLE
urllib3 module missed

### ISSUE THREAD

**Issue by JanisV** [boukendesho/opennumismat-snap#1]
Hi,

When I try run OpenNumismat from snap it crash with following error:
`ModuleNotFoundError: No module named 'urllib3'`
It is requred from version 1.9.9

**Comment by boukendesho** [comment]
Oh sorry for that, will look into it ASAP.

**Comment by boukendesho** [comment]
It has been fixed in the latest build.

You can try by switch to the edge channel. `$ sudo snap refresh opennumismat --edge`

I did a quick test and it's seems ok. If you could help me test it more I would appreciate it!

Again thanks for your report.

**Comment by JanisV** [comment]
Now it work with stable version too, if I understood snap interface correctly.
Thank you for your snap! Link will be added to https://opennumismat.github.io/open-numismat/#download 😉
