### ISSUE TITLE
Possible problem on Ubuntu 24.04

### ISSUE THREAD

**Issue by JanisV** [boukendesho/opennumismat-snap#2]
Ubuntu 24.04 has python 3.12 as default interpretator, but in snap folder `/snap/opennumismat/8/lib/python3.10` all modules for python 3.10.
Today deb-package has a same problem. System python can't find this modules and if it finds it (after creating symlink for ex), then another problem occurs - binaries for PIL and numpy not compatible with python 3.12

**Comment by boukendesho** [comment]
Cause the snap package is a container environment, it use the base's python interpretator, now this is base on core22, which is Ubuntu 22.04 LTS.

Will try to upgrade to the newest core24 which is Ubuntu 24.04 LTS base. It has the python 3.12 inside.

**Comment by JanisV** [comment]
I'm not familiar with snap. I just saw `/snap/opennumismat/8/bin/python3` that is link to system python. But judging by the startup behavior it doesn't seem to be used.
OpenNumismat can use python 3.10, but 3.12 is faster.

**Comment by boukendesho** [comment]
> I just saw /snap/opennumismat/8/bin/python3 that is link to system python.

Snapd handle those link to real path, which is a so called core snap, it based on a LTS release with minimum packages.

Now it has been migrated to core24, which means python 3.12.

You can try by switch to the edge channel. `$ sudo snap refresh opennumismat --edge`

Thank you very much for the report !

**Comment by JanisV** [comment]
Yes, it works on both Ubuntu 22.04 and 24.04
